CREATE SCHEMA IF NOT EXISTS pb_generator_test;

CREATE TABLE IF NOT EXISTS pb_generator_test.demo (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(200) NULL,
  password VARCHAR(200) NULL
);
